# Generated by Django 5.0.7 on 2024-07-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.FloatField()),
                ('hardness', models.FloatField()),
                ('solids', models.FloatField()),
                ('chloramines', models.FloatField()),
                ('sulfate', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('organic_carbon', models.FloatField()),
                ('trihalomethanes', models.FloatField()),
                ('turbidity', models.FloatField()),
                ('potability', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('ph', 'hardness', 'solids', 'chloramines', 'sulfate', 'conductivity', 'organic_carbon', 'trihalomethanes', 'turbidity')},
            },
        ),
    ]
